name: kdm_journal
description: A modern web application for traders to record, analyze, and track their trading performance with AI-powered insights.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  path: ^1.9.0
  file: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
